"""
security.py
Jordan Steele -- Security & QA Lead

Implements:
  -  Password hashing / verification (bcrypt)
  -  HMAC-SHA256 payload integrity verification
  -  Role-Based Access Control (RBAC) middleware

Designed to drop into the existing Flask app (server.py) and
multiprocessing manager backend (trivia-manager.py) with minimal
changes -- see integration notes at the bottom of this file.
"""
import bcrypt
import hmac
import hashlib
import time
import secrets
from functools import wraps
from flask import session, request, jsonify


# Password hashing & verification

def hash_password(plain_password: str) -> str:
    """
    Hash a plaintext password with bcrypt and return a string safe to store.
    A fresh random salt is generated by bcrypt for every call.
    """
    if not isinstance(plain_password, str) or len(plain_password) == 0:
        raise ValueError("Password must be a non-empty string")
    hashed = bcrypt.hashpw(plain_password.encode("utf-8"), bcrypt.gensalt())
    return hashed.decode("utf-8")


def verify_password(plain_password: str, stored_hash: str) -> bool:
    """
    Compare a plaintext password against a stored bcrypt hash.
    Returns False (never raises) on malformed input so callers can
    treat every failure path the same way.
    """
    try:
        return bcrypt.checkpw(
            plain_password.encode("utf-8"),
            stored_hash.encode("utf-8"),
        )
    except (ValueError, TypeError):
        return False


# HMAC-SHA256 payload integrity
#
# Every write-sensitive request is signed with an HMAC-SHA256 of its raw
# body. The signing key here is NOT one static secret shared by every
# browser (that was the original design, and its problem is real: a
# secret embedded in shipped JavaScript is readable by anyone who opens
# dev tools, so it stops accidental tampering but nothing else). Instead,
# issue_login_session() below generates a fresh, random, per-session
# token at login time and hands it back to the client in the login/
# register response body. Every signed request after that is checked
# against THAT session's own token (stored server-side in the signed
# Flask session, session['signing_token']), not a single global secret.
# A leaked token only ever affects the one session it was issued to, and
# it stops being useful the moment that session ends.


def sign_payload_with_token(raw_body: bytes, token: str) -> str:
    """
    Produce a hex HMAC-SHA256 signature for a request body, keyed by a
    specific session's signing token (not a global secret).
    """
    return hmac.new(token.encode("utf-8"), raw_body, hashlib.sha256).hexdigest()


def verify_signature(raw_body: bytes, signature_header: str) -> bool:
    """
    Constant-time comparison of a recomputed HMAC -- keyed by the current
    Flask session's own signing_token -- against the signature supplied
    by the client in the X-Signature header. False if there's no
    signature, or no signing token on this session (e.g. it was never
    logged in, or the session expired).
    """
    token = session.get("signing_token")
    if not signature_header or not token:
        return False
    expected = sign_payload_with_token(raw_body, token)
    return hmac.compare_digest(expected, signature_header)


def require_valid_signature(view_func):
    """
    Flask route decorator: rejects any request whose body doesn't match
    the X-Signature header, verified against this session's own signing
    token (see verify_signature() above). Apply to any route that
    accepts writes (answer submissions, quiz creation, etc) -- pair with
    @require_login or @require_role so a signing_token is guaranteed to
    exist on the session by the time this runs.
    """
    @wraps(view_func)
    def wrapper(*args, **kwargs):
        if not session.get("signing_token"):
            return jsonify({"error": "no signing token for this session -- log in again"}), 401
        signature = request.headers.get("X-Signature", "")
        if not verify_signature(request.get_data(), signature):
            return jsonify({"error": "invalid or missing payload signature"}), 400
        return view_func(*args, **kwargs)
    return wrapper



# Role-Based Access Control (RBAC) middleware


def require_role(*allowed_roles):
    """
    Flask route decorator. Usage:

        @app.route("/api/trivia", methods=["POST"])
        @require_role("teacher")
        def create_trivia():
            ...

    Blocks the request with 401 if there's no logged-in session, and 403
    if the logged-in user's role isn't in allowed_roles. Assumes the
    session dict has 'UUID' and 'role' set at login time.
    """
    def decorator(view_func):
        @wraps(view_func)
        def wrapper(*args, **kwargs):
            if "UUID" not in session:
                return jsonify({"error": "not authenticated"}), 401
            role = session.get("role")
            if role not in allowed_roles:
                return jsonify({"error": "forbidden: insufficient role"}), 403
            return view_func(*args, **kwargs)
        return wrapper
    return decorator


def require_login(view_func):
    """Lightweight decorator for routes that only need 'is anyone logged in'."""
    @wraps(view_func)
    def wrapper(*args, **kwargs):
        if "UUID" not in session:
            return jsonify({"error": "not authenticated"}), 401
        return view_func(*args, **kwargs)
    return wrapper

# Session token helpers

def new_session_token() -> str:
    """Cryptographically random opaque token for session/reconnect use."""
    return secrets.token_urlsafe(32)


def issue_login_session(uuid: str, role: str) -> str:
    """
    Call this on successful login/registration to populate the Flask
    session in one place, instead of scattering session[...] assignments
    across routes (reduces the risk of forgetting to set 'role').

    Also issues a fresh, random per-session HMAC signing token (see the
    "HMAC-SHA256 payload integrity" section above) and stores it on the
    session as session['signing_token']. Returns that token so the
    calling route can hand it back to the client in the response body --
    the client needs it to sign write-sensitive requests, and this is
    the only place it's ever transmitted, over the same HTTPS connection
    the login itself used.
    """
    session["UUID"] = uuid
    session["role"] = role
    session["idx_of_trivia_set"] = session.get("idx_of_trivia_set", 0)
    session["question_idx"] = session.get("question_idx", 0)
    session["logged_in_at"] = int(time.time())
    token = new_session_token()
    session["signing_token"] = token
    return token
