"""
security.py
Jordan Steele -- Security & QA Lead

Implements:
  -  Password hashing / verification (bcrypt)
  -  HMAC-SHA256 payload integrity verification
  -  Role-Based Access Control (RBAC) middleware

Designed to drop into the existing Flask app (server.py) and
multiprocessing manager backend (trivia-manager.py) with minimal
changes -- see integration notes at the bottom of this file.
"""
import bcrypt
import hmac
import hashlib
import os
import time
import secrets
from functools import wraps
from flask import session, request, jsonify


# Password hashing & verification

def hash_password(plain_password: str) -> str:
    """
    Hash a plaintext password with bcrypt and return a string safe to store.
    A fresh random salt is generated by bcrypt for every call.
    """
    if not isinstance(plain_password, str) or len(plain_password) == 0:
        raise ValueError("Password must be a non-empty string")
    hashed = bcrypt.hashpw(plain_password.encode("utf-8"), bcrypt.gensalt())
    return hashed.decode("utf-8")


def verify_password(plain_password: str, stored_hash: str) -> bool:
    """
    Compare a plaintext password against a stored bcrypt hash.
    Returns False (never raises) on malformed input so callers can
    treat every failure path the same way.
    """
    try:
        return bcrypt.checkpw(
            plain_password.encode("utf-8"),
            stored_hash.encode("utf-8"),
        )
    except (ValueError, TypeError):
        return False


# HMAC-SHA256 payload integrity

HMAC_SECRET_KEY = os.environ.get("TRIVIA_HMAC_SECRET", "").encode("utf-8")

if not HMAC_SECRET_KEY:
    # Fail loudly in dev rather than silently signing with an empty key.
    HMAC_SECRET_KEY = secrets.token_bytes(32)
    print("[security.py] WARNING: TRIVIA_HMAC_SECRET not set. "
          "Generated a temporary key for this process only. "
          "Set TRIVIA_HMAC_SECRET in your environment for real deployments.")


def sign_payload(raw_body: bytes) -> str:
    """
    Produce a hex HMAC-SHA256 signature for an outgoing raw request body.
    The client-side (JS) equivalent must use the same secret + algorithm.
    """
    return hmac.new(HMAC_SECRET_KEY, raw_body, hashlib.sha256).hexdigest()


def verify_signature(raw_body: bytes, signature_header: str) -> bool:
    """
    Constant-time comparison of a recomputed HMAC against the signature
    supplied by the client in an 'X-Signature' header.
    """
    if not signature_header:
        return False
    expected = sign_payload(raw_body)
    return hmac.compare_digest(expected, signature_header)


def require_valid_signature(view_func):
    """
    Flask route decorator: rejects any request whose body doesn't match
    the X-Signature header. Apply to any route that accepts writes
    (answer submissions, quiz creation, etc).
    """
    @wraps(view_func)
    def wrapper(*args, **kwargs):
        signature = request.headers.get("X-Signature", "")
        if not verify_signature(request.get_data(), signature):
            return jsonify({"error": "invalid or missing payload signature"}), 400
        return view_func(*args, **kwargs)
    return wrapper



# Role-Based Access Control (RBAC) middleware


def require_role(*allowed_roles):
    """
    Flask route decorator. Usage:

        @app.route("/api/trivia", methods=["POST"])
        @require_role("teacher")
        def create_trivia():
            ...

    Blocks the request with 401 if there's no logged-in session, and 403
    if the logged-in user's role isn't in allowed_roles. Assumes the
    session dict has 'UUID' and 'role' set at login time.
    """
    def decorator(view_func):
        @wraps(view_func)
        def wrapper(*args, **kwargs):
            if "UUID" not in session:
                return jsonify({"error": "not authenticated"}), 401
            role = session.get("role")
            if role not in allowed_roles:
                return jsonify({"error": "forbidden: insufficient role"}), 403
            return view_func(*args, **kwargs)
        return wrapper
    return decorator


def require_login(view_func):
    """Lightweight decorator for routes that only need 'is anyone logged in'."""
    @wraps(view_func)
    def wrapper(*args, **kwargs):
        if "UUID" not in session:
            return jsonify({"error": "not authenticated"}), 401
        return view_func(*args, **kwargs)
    return wrapper

# Session token helpers

def new_session_token() -> str:
    """Cryptographically random opaque token for session/reconnect use."""
    return secrets.token_urlsafe(32)


def issue_login_session(uuid: str, role: str):
    """
    Call this on successful login/registration to populate the Flask
    session in one place, instead of scattering session[...] assignments
    across routes (reduces the risk of forgetting to set 'role').
    """
    session["UUID"] = uuid
    session["role"] = role
    session["idx_of_trivia_set"] = session.get("idx_of_trivia_set", 0)
    session["question_idx"] = session.get("question_idx", 0)
    session["logged_in_at"] = int(time.time())
